version: "2"

services:
  gla_sails:
    build: .
    environment:
      - SWARM_HOST=${SWARM_HOST}:3376
    depends_on:
      - mongo

  gla_angular:
    build: ../gla-angular
    ports:
      - 3000:3000
    depends_on:
      - gla_sails

  mongo:
    image: mongo
