version: "2"

services:
  glasails:
    image: glapp/gla-sails
    environment:
      - SWARM_HOST=${SWARM_HOST}
      - MONGO_HOST=mongo
    ports:
      - 1337:1337
    volumes:
      - /swarmcerts:/root/.docker/machine/certs
    depends_on:
      - mongo

  glaangular:
    image: glapp/gla-angular
    environment:
      - SAILS_PORT=1337
    ports:
      - 80:3000
    depends_on:
      - glasails

  mongo:
    image: mongo

  mape:
    image: glapp/mape
    environment:
      - SAILS_HOST=glasails
    depends_on:
      - glasails
